### ISSUE TITLE
Discussion topic: Set up global git repository for packages?

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-schema#15]
So, didn't know where else to put this, so in order to not forget I thought I open an issue on the schema repo.

Originally we set out to first define the package format, then establish tooling, then worry about making a public master-repository and database for download, website access etc.

I now thought that it might actually help us curate the datasets if we find a way to use git to maintain not only the schema and the tools, but also the data itself.

This seems rather attractive for the metadata (janno-, package- and bib files), where git would allow us to commit changes and have a better overview on what still needs fixing, on getting community help for curation, etc.

The big "elephant in the room" question, of course, is how to deal with the genotype data, which is large. I see generally two options here:
1) Do not keep the genotype data in git, but modify the package format to keep md5 hashes of the genotype files in the package file, or something like that, and then simply put the duty on the user to keep genotype files untracked.
2) Stick genotype files into git, alongside everything else. These will be large files, and there are some extensions available for this kind of stuff, but I'm not sure how practicable they are. We might also - in that case - consider using the GWDG hosted gitlab, in order to avoid swamping GitHub with such large data. We should also see how large the files actually are, whether we can perhaps somehow pack the bim files (currently they are unpacked text files), or whether we should split up the large packages (like our massive pre2018 package) into smaller ones in order to for them to be more compatible with git.

What say you?

**Comment by nevrome** [comment]
I think both tracking the data with git and making it publicly available would be a huge advantage for the project. Having the data in a github project would allow for all sorts of cool things, including package validation on PRs!

I fear Git Large file storage is not terribly user friendly and storing the data on Github is not feasible because it imposes both strict storage and bandwidth limits. 

What about the following solution: We store the meta text files (POSEIDON.yml, .janno, .bib, ...) in a repo on github. The actual genetic data is stored on an institute server. The POSEIDON.yml on github contain hyperlinks to the genetic data files. Our tooling gets adapted to work not just with local paths, but with hyperlinks, and gets some caching abilities.

**Comment by stschiff** [comment]
Right, thought in the same direction... I agree that the hyperlink solution is nice, but it also means some additional complexity in our tooling... maybe that's worth in the long run. I still think, btw, we should store the hashes in the package definition file, to ensure consistency (since we're not tracking the genotype files then).

**Comment by stschiff** [comment]
And we need to think where to host the genotype files... nextcloud might work for now, but in the long run we need some more secure repo server...

**Comment by nevrome** [comment]
Right - the hashes are a good idea.Do we have to go through Nextcloud though? We could as well get an own subdomain to host the data there. Maybe even via ftp?For some papers the data might already be hosted properly?

**Comment by stschiff** [comment]
You're right, hosting on our yet-to-be dedicated website is the best solution. I'm strongly for self-hosting, we certainly don't want to rely on other people's homepage... we also want to ensure that nothing changes behind our backs. I still think - btw - that we should at least make a quick check how large these files actually are, and whether it's really impractical to work with git.

**Comment by nevrome** [comment]
Ja - own space is best. I personally would prefer a very simple ftp server with public read permissions. No fancy homepage. Just  naked, pure data. 

The data size is too big for Github (see list in slack channel). Github already gets nervous at a file size of 50mb.

**Comment by nevrome** [comment]
One additional issue brought up in the meeting today were legal concerns and licensing for  such a data archive.

**Comment by stschiff** [comment]
I think this is on a good way, as by a phone call today between me and Clemens. As soon as we have the new package repos set up we can close this.
