### ISSUE TITLE
Numerical columns in janno file cannot take care of multiple fileds

### ISSUE THREAD

**Issue by wangke16** [poseidon-framework/poseidon-schema#16]
Sometimes I have two libraries/sample materials for one individual, therefore in such case I have two fields separated by semicolon in columns such as Damage, Xcontam, Xcontam_sterr, mtContam. "poseidon2 validate" reports errors aback in such case. How would you suggest to resolve this?

**Comment by wangke16** [comment]
@stschiff  even in the case of one individual from left petrous and right petrous data (different archeological materials)? I should report for the dominant one (the library with more data)?

**Comment by nevrome** [comment]
@stschiff Shouldn't #14 be rejected as well in this case?

**Comment by stschiff** [comment]
Hmm. Good Point. Well, perhaps it's easy to simply allow for this. @nevrome allowing for multiple entries in the fields that @wangke16 suggested wouldn't break compatibility with previous datasets, right?

**Comment by nevrome** [comment]
Theoretically not, no. So this could be an easy change. Though we might have semantic problems, when users made decisions in the past based on the assumption that this was simply not possible.

Which columns exactly should be changed, @wangke16? Just the ones you mention? Or does this affect others as well?

By opening this up it will become more difficult to do analysis with this data. Users will have to make decisions about which libraries to use. And they will have to deal with more complex data structures (e.g. list columns in R).

I also wonder how we indicate the implicit hierarchy expressed in multiple libraries. Are they from the same extract? From the same bone? Poseidon is a very simple format strictly focused on the unit "human individual" and we will not be able to express information beyond a certain level of complexity.

**Comment by wangke16** [comment]
Here are the columns I got error with (because two samples was treated as different individuals but eventually confirmed to be the same individual):
Date_C14_Labnr, Date_C14_Uncal_BP, Date_C14_Uncal_BP_Err, Endogenous, Damage, Xcontam, Xcontam_stderr, mtContam, mtContam_stderr

I dont agree with this though - "By opening this up it will become more difficult to do analysis with this data." The final data (genotype) used for downstream analyses is merged across libraries anyway. Having per-library information just provides users more details on data preprocessing statistics.

**Comment by nevrome** [comment]
`Date_C14_Labnr`, `Date_C14_Uncal_BP` and `Date_C14_Uncal_BP_Err` do support multiple entries separated with `;`. If you saw an issue in these columns we should discuss this separately.

**Comment by wangke16** [comment]
I see. then I think it's because of white space I used after `;`

**Comment by stschiff** [comment]
(Edited!)
I think the following would be fields that theoretically have a "per-library" semantic:
- Endogenous
- UDG
- Library_built
- Damage
- Xcontam
- Xcontam_stderr
- mtContam
- mtContam_stderr

**Comment by stschiff** [comment]
and we could - theoretically - even demand that the `No_of_Libraries` field corresponds to the number of values in those columns...

**Comment by nevrome** [comment]
What about the following variables:
- Genetic_Sex
- Nr_autosomal_SNPs
- Coverage_1240K
- MT_Haplogroup
- Y_Haplogroup

Couldn't they also differ by library?

**Comment by stschiff** [comment]
No, those would be consensus calls, as they are inevitably statements about the individual, rather than a library. Of course, those things can be estimated separately from each library, but every author needs to in the end make a single call for those. The same is not true for things like damage, endogenous DNA or contamination, which are typically reported per library.

**Comment by nevrome** [comment]
Please see #17 for a suggestion how to update the janno definition.
