### ISSUE TITLE
Determining Date_BC_AD_Median, Date_BC_AD_Start and Date_BC_AD_Stop

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-schema#18]
I got some user feedback from @MaiteRivollat: She has radiocarbon dates but does not know how exactly the convenience columns `Date_BC_AD_Median`, `Date_BC_AD_Start` and `Date_BC_AD_Stop` should be calculated from them. I believe this is a problem other user will have as well in the future.

I quickly hacked something ugly together for her based on old code fragments donated to me by @MartinHinz, but we will need a more permanent solution. 

Expressing one or even multiple radiocarbon dates dates with only three numbers is insufficient no matter what. We have to find a compromise we can live with.

```
library(magrittr)

bol <- 1950
threshold <- 0.025

cur_xs <- c(3000, 3500, 3300) 
cur_errs <- c(100, 50, 200)

cur_raw_calibration_output <- Bchron::BchronCalibrate(
  ages      = cur_xs,
  ageSds    = cur_errs,
  calCurves = rep("intcal13", length(cur_xs))
)

density_tables <- lapply(
  cur_raw_calibration_output,
  function(y) { 
    tibble::tibble(
      age = as.integer(-y$ageGrid + bol),
      densities = y$densities
    )
  }
)

sum_density_table <- dplyr::bind_rows(density_tables) %>%
  dplyr::group_by(.data[["age"]]) %>%
  dplyr::summarise(
    sum_dens = sum(.data[["densities"]])/length(density_tables),
    .groups = "drop"
  ) %>%
  dplyr::right_join(
    .,
    data.frame(age = min(.[["age"]]):max(.[["age"]])),
    by = "age"
  ) %>%
  dplyr::mutate(
    sum_dens = tidyr::replace_na(.data[["sum_dens"]], 0)
  )

a <- cumsum(sum_density_table$sum_dens) # cumulated density
bottom <- sum_density_table$age[max(which(a <= threshold))]
top <- sum_density_table$age[min(which(a > 1 - threshold))]
center <- sum_density_table$age[which.min(abs(a - 0.5))]

result_table <- sum_density_table %>% dplyr::mutate(
  two_sigma = .data[["age"]] >= bottom & .data[["age"]] <= top,
  center = .data[["age"]] == center
)

Date_BC_AD_Median <- result_table[["age"]][result_table[["center"]]]
Date_BC_AD_Start <- result_table %>% dplyr::filter(two_sigma) %>% head(1) %$% age
Date_BC_AD_Stop <- result_table %>% dplyr::filter(two_sigma) %>% tail(1) %$% age
```

**Comment by MartinHinz** [comment]
Agreed with what Clemens said! Every point estimate from a probability range has an overwhelming probability of being wrong! The code can certainly be made more elegant, but it is functional. It should be noted, however, that here the weighted average is calculated, not the median! The median would simply be the mean value between start and stop, as far as I understand it.

For more information see the article by [Telford et al. 2004](https://journals.sagepub.com/doi/10.1191/0959683604hl707fa). It also says that the point estimate by the weighted average is the best estimate, but still a rather bad one. Does that help?

**Comment by nevrome** [comment]
Thanks Martin - that paper is spot on.

But are you sure that is not the median? According to my understanding of this definition from Wikipedia it should be:


![image](https://user-images.githubusercontent.com/10789038/94342175-8de47080-000f-11eb-8ad6-0bbabce885ad.png)

**Comment by MartinHinz** [comment]
Damn, your right. Should have looked more precise to the code, I thought you have 'taken' another piece of my legacy wrongdoings...

**Comment by stschiff** [comment]
yes, we need the 0.025, 0.5 and 0.975 quantiles (and thereby the 95% credibility interval), which seems to be what the code above is doing. I don't think there is anything hacky about this. If we transparently communicate that these three numbers summarise the cumulative probability distribution, it's fine. We're decidedly _not_ replacing the distribution with a point estimate.

Clemens, did you imagine this code going into your Poseidon2 R package?

**Comment by nevrome** [comment]
Well - the command line interface of poseidon2 could get a module `quickcalibrate` that wraps the code above. 

Maybe like this

```
$ poseidon2 qcal 3000,3500,3300 100,50,200

Date_BC_AD_Start Date_BC_AD_Median Date_BC_AD_Stop
... ... ...
```

But I don't want to add general calibration functionality. Much more sophisticated tools exist for that already. One could even think about adding a specific output option to e.g. [`calibrator`](https://github.com/ISAAKiel/calibrator) to keep this out of poseidon2 completely.

**Comment by stschiff** [comment]
I like this as a pragmatic idea.

**Comment by nevrome** [comment]
Is implemented now.
