### ISSUE TITLE
Make Janno-File non-mandatory

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-schema#19]
I'm aware that this will seem like heresy to some of you, but I think there are good reasons to make the janno-file optional.

Background is the possibility to "hook in" your own data into an existing Poseidon dataset. Consider you have just started your project, you have a bunch of individuals with genotypes, and would like to start analysing that data together with the large Poseidon dataset (for example using `poet`, my new fstats analysis tool). For that to work, `poet` currently supports an arbitrary amount of Poseidon base directories in which to look for packages. So, for example, if the main poseidon package repository is at `/projects/poseidon/ancient` or so, and your own little poseidon mini-module is under `~/myproject/package`, then you can run `poet fstats --baseDir /projects/poseidon --baseDir ~/myproject/package --stat ...`. 

For this to work as easy as possible, I'd like to make it as easy as possible to create an adhoc-poseidon package. If the janno-file were optional, that would be super easy, as all it would take is a quick `poseidon.yml` file listing the three genotype files and some trivial meta-data.

Of course, for any public release, or even contribution to our main package repository, we would insist on janno files...

What do you think?

**Comment by stschiff** [comment]
Alternative would be to allow `poet` to read in a poseidon package without a janno file, just issuing a warning...

**Comment by nevrome** [comment]
IMHO this is not a question for the standard. A Poseidon v.2 package absolutely needs context data as you state yourself:

> Of course, for any public release, or even contribution to our main package repository, we would insist on janno files...

Your tool on the other hand can very well be used without a .janno file and we could maybe change the validator implementation in poseidon2 to make sure it does not stop immediately when no .janno file is detected. Our soft validation approach is well suited for such hacks.

**Comment by stschiff** [comment]
Yes, that's a valid viewpoint. It's a bit similar to my proposal for handling multiple packages of the same name. In the end you're right, we can implement such semantics within the tools that parse packages.
