### ISSUE TITLE
Eigenstrat data format

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-schema#20]
Poseidon packages should also be able to store genetic data not only in PLINK binary, but also EIGENSTRAT format.

This requires significant updates of the tooling.

**Comment by stschiff** [comment]
Right. I think that should definitely possible and in the format, but of course your tooling could make transparent that you're currently not supporting `Eigenstrat`... as we discussed in other places, tools have some range of freedom to decide which parts of the format they implement and support (for example `poseidon-hs` currently allows janno files to be empty or non-existent)... as long as there are clean error messages or warnings.

**Comment by nevrome** [comment]
Now that I think of the consequences I fear that opening the format and allowing for more and more flexibility will eventually make it way (!) less easy to use and less compatible. Imagine that: "I can't merge these two poseidon packages, because the software supports only one format." That's horrible. 

I say it now: We should only allow one format and that should not be a binary, but a human readable format. Fight me!

**Comment by stschiff** [comment]
Hmm, fair enough. But the human readable format (which would be Eigenstrat) is far larger than PLINK. So Plink is better for compressed distribution of packages, while Eigenstrat is typically the format that comes out of genotyping, for example with `pileupCaller`.

**Comment by nevrome** [comment]
I'm aware of the size difference but I don't know the dimensions. Maybe it is indeed infeasible to use a non-binary format for data distribution.

But 
- a human readable format is significantly better from a long term storage perspective
- a human readable format makes the implementation of software using and manipulating this data more straight forward
- normal archiving (.zip, .tar.gz, etc.) might be an alternative solution to the data distribution issue

**Comment by stschiff** [comment]
Fair points! Yes, we urgently need a meeting to fix a roadmap. I also want to move forward with putting our master-repo into GitHub, which will require some decisions about remote-loading of genotype data (see #15).

**Comment by stschiff** [comment]
One argument, by the way, for supporting two formats, is that it makes it much easier for folks to "hook in" their own private datasets for joint analyses, as my vision for tooling goes. So one solution would be to support both formats in the specification, but at the same time decide for constraints on the master-repository that we are building.

**Comment by nevrome** [comment]
I started to think about the consequences of this possible change (allowing multiple file formats) for poseidon2 in https://github.com/poseidon-framework/poseidon2/issues/14. Some (first) additional questions:

- Which one is the primary format? The standard should favor one format as a default output for the merge module.
- Do we allow poseidon v.2 packages to hold the genetic data in multiple formats simultaneously? That would mean the validator needs cross checking abilities to make sure the data in all formats is equal.

**Comment by nevrome** [comment]
In the meeting on 2020-10-09 we decided to limit Poseidon v.2 to the plink binary format (.bed + .bim + .fam) for the moment.

**Comment by stschiff** [comment]
OK, let's close this then and revisit if need be.
