### ISSUE TITLE
Idea: Add a more verbose description how the .janno+.yml columns should be filled

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-schema#23]
#11, #16 and #18 have shown that it can be tricky to figure out how the columns of a `.janno` file should/could be filled. 

I suggest we add some text that explains this in more detail, including actual workflows to derive the values we would like to see from raw data. 

This is especially important if we want people outside of the MPI-SHH to adopt this format.

**Comment by stschiff** [comment]
This also should be resolved with proper documentation on the planned webpage.

**Comment by nevrome** [comment]
The proposed documentation web page exists now.
