### ISSUE TITLE
SNP names in .bim file

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-schema#25]
I just learned from Joscha that there are different ways to express the names of SNPs in the .bim file, e.g. `rs3934834` or `1_1003629` (chromosome number _ position).

We have to define which one is the right one for poseidon. Probably the `rs...` notation is more common in the data we have so far.

**Comment by AyGhal** [comment]
The correct way is rs3934834, which is helpful to find SNPs in other databases. Also all poseidon packages are based on that format.
I think with the update in pileupCaller we should completely get rid of simple.snp (chr_position) format.

**Comment by nevrome** [comment]
Alright - thanks for the fast reply - `2020_Rivollat_FranceGermany` was still in the old format and I tried to fix it now. Still testing. We should document this somewhere.

**Comment by stschiff** [comment]
Right. Having said that there is no rule that says that SNP IDs need to follow any specific naming scheme. The `rsXXX` scheme is established, but people in non-human model-orgamisms will have different policies. But certainly for the human data that we're dealing with here, it's good practice to stick to the rs system.

**Comment by stschiff** [comment]
And yes, we should document that on the homepage under a "For package authors" section.

**Comment by nevrome** [comment]
This is now documented on the extended documentation page: https://poseidon-framework.github.io/#/genotype_data?id=snp-ids
