### ISSUE TITLE
X contamination

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-schema#26]
Ayshin recently explained me that we report

1. X contamination for female individuals 
2. negative X contamination values (as sometimes produced by e.g. ANGSD)

as `n/a`  in the `.janno` file. This decision was made in one of the internal meetings. 

Do we want to rethink this again? Otherwise it should be documented.

**Comment by stschiff** [comment]
I think this decision makes still sense. As a key guideline, we want those numbers to transcend the specific choice of tooling that the package author may have used to estimate contamination. Whether ANGSD, or Schmutzi, or AuthentiCT, or what not: In the end the number that gets entered here must be interpretable in the traditional sense of a contamination. Negative values are not interpretable, so then rather one would put `0.0` with a small error bar (if one is convinced that that's right thing), or `n/a`. Similarly, ANGSD simply can _not_ estimate contamination for females, so `n/a` is correct in that case.

**Comment by stschiff** [comment]
Ah, wait, I see. We've actually called this column `Xcontam`, so it's clear that it refers to ANGSD. Well... yes OK, let's document it.

**Comment by stschiff** [comment]
As a matter of fact, I think we should rename this to `nucContam` to be clear that it's the nuclear contamination estimate, rather than the mitochondrial one. What do you think @AyGhal and @wolfgangaroo?

**Comment by wolfgangaroo** [comment]
I'd leave Xcontam, nothing wrong with that. Also, we might get a 'true' nucContam estimate via AuthentiCT one fine day.

**Comment by stschiff** [comment]
But that's exactly the point: If we want that contam field in the future to be a general nucContam field, we might as well switch to it now. In the end, what ANGSD calculates is the nuclear contamination, not the "X chromosome contamination" which biochemically makes no sense.

**Comment by wolfgangaroo** [comment]
Well, you could argue that the allele frequency distribution on the X is different from the autosomes...

**Comment by wolfgangaroo** [comment]
Either way, fine with me.

**Comment by stschiff** [comment]
We decided that
i) we keep the column namings for now
ii) we translate negative values to 0.
@nevrome please update the docs. Thanks.
