### ISSUE TITLE
Relax Janno Column requirements to enable progress with backwards-compatibility

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-schema#29]
I think we should consider relaxing the exact layout of Janno-files. I propose 
a) to relax column order specification, and
b) column requirements

Currently, we require Janno-Files to follow an exact layout, with a specified number of columns, each with a specific name. Every column must be there, and the order must adhere to our format. I believe now that we have powerful tooling available, these requirements aren't so important anymore. In principle, optional columns could be left out by a user, and the order doesn't matter either.

Downside: This would mean that one cannot anymore simply concatenate Janno-Files and expect the outcome to again be a valid janno-file. I believe this is only a minor issue as long as we have tooling that allows to merge Janno-files properly, like `janno forge`. 

Upside: We can continue to develop the format further, without loosing backwards-compatibility: The moment when we start adding optional columns that we didn't have before, we can just update the format and all the old Janno-Files will still be valid. This would also make it simpler for Teams like the Harvard-Team to quickly adapt their existing Anno-Files (which also change continuously) to bring them into Janno-Format.

We could even start allowing additional columns that we haven't specified. Strictly that wouldn't break anything, we would just adapt our parser that any fields that aren't recognised are simply not parsed.

Just some thoughts...

**Comment by stschiff** [comment]
We discussed this during a meeting and overall agreed to this change, although we'd like to first make sure `trident` works with it before we officially relax the constraints and update the schema.

**Comment by nevrome** [comment]
Both trident and poseidonR should now be able to handle both missing (except for `Individual_ID`, `Group_Name` + `Genetic_Sex`) and additional columns (so columns not defined here). They now also treat `""` as `NA`, not only `"n/a"`.

The format definition can be updated with this in mind when https://github.com/poseidon-framework/poseidon-framework.github.io/issues/6 is reversed for the schema repo.

**Comment by nevrome** [comment]
This is done.
