### ISSUE TITLE
SNP-Set specification in YAML file

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-schema#33]
There currently is no systematic way to query the specific SNP list of the genotype data. While we do have a column named "Data_Type" in the Janno file, which can be "Shotgun", "1240K", "OtherCapture" and so on, this doesn't imply the SNP set itself. For example, a sample can be "Shotgun" but still be represented by a 1240k SNP list.

It would be very useful to be able to check the SNP set upfront, because - for example - you might have a dataset with very low coverage and you know that you would want to squeeze out as much as possible, so would like to forge only packages with a full 1240K SNP list and not only Human Origins. I would suggest to add an optional field into the `genotypeData` object in the YAML file called `snpList` with restricted values, such as `HO`, `1240k` and in the future maybe even "1000G" if we allow genotype data to be of even denser format.

**Comment by nevrome** [comment]
But shouldn't this information be documented on a sample/individual-wise level in the .janno-file? What if somebody works with a forged package that merges multiple publications with different SNP sets?

**Comment by stschiff** [comment]
Ah, that is a good point. Yes. But then this would also apply to #32, so the data preparation info, which we're currently contemplating of putting into the yaml file.
