### ISSUE TITLE
Change `Data_Type` to `Capture_Type`?

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-schema#36]
Our decision to name the field indicating whether library was captured or not `Data_type` is terrible. Such a generic name for a very specific information is clearly bad practice. Shall we dare making a breaking change at this point and rename that to `Capture_type` (which would then include `Shotgun`, as previously)?

**Comment by stschiff** [comment]
I think the ship has sailed on renaming columns... we have too many packages already written. Shall I close this?

**Comment by nevrome** [comment]
Hm - I think we will change the format even more in the future - and so far we still have few users (I assume).

Let's just collect some of these changes in a PR and then release them eventually. Of course we have to make some changes in trident, but poseidonR can easily be updated and for the repo we have `trident update`.

**Comment by stschiff** [comment]
Yeah, fair enough. I thought we're afraid of format/schema changes that impose breaking changes. Of course, this one would be actually quite vicious because it wouldn't be breaking, but simply set all these columns with the new name to NA. Need to think about how to introduce changes like this and make users gently aware of it.

**Comment by nevrome** [comment]
#42
