### ISSUE TITLE
More clearly define meaning of `Coverage_1240k` 

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-schema#37]
I believe that the current Janno field `Coverage_1240k` has its uses, as it gives the reader a clear and comparable idea of the genome-wide coverage of a sample. That this coverage be evaluated on 1240k SNPs is independent of the question whether the specific genotype data in a package indeed lists all 1240k SNPs or some other SNP set (say, HumanOrigin or 1000 Genomes in the future). I think we don't need to change this, but should improve the documentation on that front, because the hard-coded `1240k` in the table header might be confusing for users who would like to work with genotype data on super- or subsets of 1240k.

**Comment by nevrome** [comment]
`Coverage_1240k` was replaced by `Coverage_on_Target_SNPs` in Poseidon 2.5.0

The documentation [here](https://poseidon-framework.github.io/#/janno_details?id=data-yield) describes this field as follows:
> The Coverage_on_Target_SNPs column reports the mean SNP coverage on the target SNP array (e.g. 1240K) for the merged libraries of this sample. To calculate the coverage it is necessary to determine which SNPs are covered how many times by the mapped reads. Individual SNPs might be covered multiple times, whereas others may not be covered at all by the highly deteriorated ancient DNA. The coverage for each SNP is therefore a number between 0 and n. The statistic can be determined for example with the [QualiMap](http://qualimap.conesalab.org/) software package. In case of multiple libraries, the coverage can be given as a mean across all of them.

Please reopen this issue if it's still relevant and if you would still like to adjust this documentation.
