### ISSUE TITLE
Identifiers

### ISSUE THREAD

**Issue by xrotwang** [poseidon-framework/poseidon-schema#43]
The definition of `Individual_ID` seems inconsistent:

> The Individual_ID column has to represent each sample with a world-wide unique identifier string equal to the identifier used in the respective accompanying publication.

If `Individual_ID` has to *equal* the identifier used in the publication, how can one make sure it's also a UUID?
The specification goes on to say

> There is no central authority to issue these identifiers, so it remains in the hand of the authors to avoid duplication. The Individual_IDs are also employed in the genetic data files and therefore have to adhere to certain constraints. 

which might create even more problems to reconcile "identifier as in publication" with what Poseidon wants. From my experience, I'd recommend to distinguish *local IDs* and global UUIDs explicitly, and specify all of the constraints for the UUID.

**Comment by stschiff** [comment]
Fair enough. Well, Clemens and I have pondered some kind of "Poseidon" sample ID, which we declare once a new package is taken into our central repository. That may make sense at some point.

**Comment by stschiff** [comment]
This was discussed again on Oct 14.
- AADR has the concept of `Version ID` vs `Master ID`, where the `Master ID` is arguably a unique identifier. We could adopt something like this, which we could then call `Poseidon Master Individual ID` or something more with a ring to it.
- Alternative would be to introduce a column called `Related_To` and `Degree_of_relatedness` which would act as key into the same table to describe relationships.

Preliminary decision:
- Change `Individual ID` to `Poseidon ID`
- Introduce `AKA` column which lists multiple other names the individual is known as (list column)
- Introduce `Related_To` column, also list
- Introduce `Relation_Type` column, also list, choice field something like `Identical`, `1st degree`...
