### ISSUE TITLE
Endogenous

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-schema#5]
In the last days/weeks there have been extensive discussions at the institute how exactly the **% endogenous DNA** should be calculated to be most correct and informative. My understanding was, that there was so far no consensus, because multiple approaches are equally valid. This is unfortunately not just about the method, but also about semantics and what that value actually means. 

Right now the **Endogenous** column of a `.janno` file is defined as

> % endogenous DNA for the SG libraries, as estimated by EAGER for the best library (in percent), not on target and no quality filter

That would be fine for data produced in house. But poseidon2 packages should be generally applicable and other authors may have chosen other methods to calculate the % endogenous DNA value.

Is it therefore necessary to soften the column definition to also allow for other ways to calculate it? How do we deal with the resulting loss of comparability?

**Comment by stschiff** [comment]
Good point, and something to discuss in today's meeting. In my view, we should give a recommendation how to calculate this, but we can't force people to use a specific calculation method if they have established pipelines. In most cases, the different ways to calculate this will be rather similar. Only in a few edge cases there might be an issue.

Generally, I would suggest we follow Eager's standard way of dividing the mapping reads by the reads attempted to map, after length filtering. As I have argued, this may not always be the "best" way to compute this, but at least for Jena data it's going to be what we have in most cases. It's clear that the janno file in its current form necessarily has to make compromises. We voluntarily did not want to report Poseidon packages in a completely reproducible way, in the sense that it is entirely clear how all the data was generated from the raw sequencing data. The Poseidon v2 format is itself a compromise that starts reporting data from genotypes onwards, so the user will have to "believe" all the processing that comes before that.

So all in all I would suggest we augment the column description with a bit more detail how we calculate this number in Eager. But happy to discuss.

**Comment by nevrome** [comment]
Just a technical remark: The variable description in the definition table (`janno_columns.tsv`) column might be overwhelmed by this and future clarifications. Maybe we add a section with information about individual variables to the README and shorten the information in the table to a very brief definition.

**Comment by nevrome** [comment]
Addresses by #6
