### ISSUE TITLE
Twist capture array

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-schema#52]
@hringbauer made us aware of a promising, new capture array/snp set that could become popular in the field: "Twist" as presented in [this publication](https://doi.org/10.1101/2022.01.13.476259 ).

We should probably add this to the options in
- the `snpSet` field in the POSEIDON.yml file
- the `Capture_Type` column in the .janno file

Very fortunately, Twist seems to be a perfect superset of 1240K (thanks for the help with finding this crucial bit of information, @JoschaGretzinger):

> For the Twist Ancient DNA reagent, we began by attempting to bait all 1,233,013 SNPs in the 1240k reagent. We then added additional content to target SNPs of phenotypic significance or SNPs improving characterization of variation on the Y chromosome.

This will allow for another neat addition to the [forge logic](https://github.com/poseidon-framework/poseidon-hs/blob/796a98e264194ee720336c03c004d6abf313adef/src/Poseidon/GenotypeData.hs#L122-L130) in trident.

**Comment by stschiff** [comment]
Yes definitely. At the latest when we add the first dataset with that SNP set to the public repo.

**Comment by stschiff** [comment]
As discussed on Slack, I think we do at this point not have to consider a different snpset, but should prepare for additional fields in the Janno-file column `Capture_Type`.

**Comment by stschiff** [comment]
At least with respect to the Capture type, this should be resolved with #54
