### ISSUE TITLE
Individual_ID vs. Poseidon_ID

### ISSUE THREAD

**Issue by xrotwang** [poseidon-framework/poseidon-schema#53]
This repos mentions the [Individual_ID column](https://github.com/poseidon-framework/poseidon2-schema#the-janno-file) in the `.janno` file, whereas the linked [details page](https://poseidon-framework.github.io/#/janno_details) talks about `Poseidon_ID`.

**Comment by nevrome** [comment]
Ah - thanks. I'll fix it. It's a pain to keep all these different documentation pieces in sync.

**Comment by nevrome** [comment]
Should be fixed in 9ea7766ce0d710fd44f86feeeb2abe25f3cd3b0c

**Comment by xrotwang** [comment]
I came to consider this pain a feature. It makes sure standards are conservative :)

**Comment by nevrome** [comment]
Every change in the Poseidon standard will have consequences for data and code across 5-6 different repos/tools. It's fascinating, how slow the development gets at some point.
