### ISSUE TITLE
Additional columns for ENA tables

### ISSUE THREAD

**Issue by TCLamnidis** [poseidon-framework/poseidon-schema#58]
# Needed additional columns
 - Library_Built/Strandedness
 - UDG per library
 - Library strategy (SG vs capture)
   - catch here is how it affects the processing. Either merge it all then we lost the WGS (needed for endogenous), or we keep separate, then have high number of "libraries" and potential leftover duplicates.

**Comment by nevrome** [comment]
Can we use the data types from the .janno file? So define the columns exactly the same as there? `mixed` would probably be pointless here, right?

**Comment by stschiff** [comment]
Yes, and I think - as in Janno - they wouldn't be List columns here, but single entries per row in the table. And indeed, "mixed" doesn't make sense, although I could see whether sometimes we might want "other"?

**Comment by nevrome** [comment]
Right - list columns are not necessary here. And `other` makes sense, but `mixed` doesn't. So that leaves us with the following new .ssf columns:

- `library_built`: ds;ss;other
- `udg` minus;half;plus;other
- `capture_type` Shotgun;AnyCapture

Or is `library_strategy` already enough and we don't need an additional `capture_type`?
And what do we do with `Source_Tissue` in the .janno file, which is already a list column for library-wise entries?

**Comment by TCLamnidis** [comment]
At present, there are only double- and single-stranded libraries, so `other` library_built does not really make sense.

**Comment by nevrome** [comment]
In principle you're right, but `other` is a measure to make things future-proof. I could be convinced, but then what about `UDG`? Is there another way to apply that or shall we remove `other` there as well?

**Comment by TCLamnidis** [comment]
To my knowledge there is no other UDG type either, and hence `other` should be avoided also, though who's to say what the future holds.

**Comment by nevrome** [comment]
Ok - in the published_data repository `UDG` is never set to `other` and `Library_Built` only twice, both when the authors actually wanted to express `mixed`. I'll remove the `other` option and add `mixed` for `Library_Built`.

**Comment by stschiff** [comment]
Closed with the latest PR vor 2.7.0 #57
