### ISSUE TITLE
X-Contamation specification

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-schema#9]
Clemens told me yesterday about the error range of the xContamination in David's table. I speculated that this is probably the 95% range of a beta-distribution. My argument is as follows: ANGSD x-contamination provides a point estimate and a standard error. The usual way to interpret that is with a Gaussian distribution with mean=point estimate and std-dev=std-error. However, here we are dealing with a quantity that is constrained to between 0 and 1. The most parsimonious (i.e. highest Entropy) distribution on the interval between 0 and 1 with a given mean and variance is the beta-distribution. So if we wanted to translate David's range to our point-estimate and std-error, we'd need to convert the 95% range of the beta-distribution to the corresponding std-deviation of a normal distribution. The more I think about it, however, the more I think that David's approach is actually cleaner. It makes no sense, for example, to talk about a contamination of - say - 1% with a 4% std-err, as that would include negative values. David's range estimate is great, because it lets the user see whether the contamination estimate is significantly greater than 0 or not. If the 95% range includes 0, the estimates are consistent with there being no contamination.

So...

1. Wolfgang, could you perhaps email David and Shop and others and ask whether the interval is indeed the 95% interval of a beta-distribution?
2. What do we do with our contamination reporting in Poseidon? Shall we stick with point-estimate and std-err, as reported from ANGSD? Or shall we switch to the range as given by David's anno file? The first is easier for us and maintainers (because copy-paste from ANGSD-output), the second is more useful for analysts of the data.

**Comment by stschiff** [comment]
Update: The range could also simply be the 95% (i.e. 2*stderr range around the mean) of a truncated normal. So you would just set the lower limit to zero if it gets negative. Also easy to check.

**Comment by nevrome** [comment]
The truncated normal theory would have the consequence that the difference between mean and the upper and lower boundary given is equal, ja? If yes, than this theory looks pretty valid in my eyes:

```
library(magrittr)

#### get data ####

anno <- data.table::fread("~/Desktop/v42.4.1240K.anno", na.strings = c("..", "n/a (<200 SNPs)"))

xcontam <- anno %>% dplyr::transmute(
  xcon = `Xcontam ANGSD MOM point estimate (only if male and ≥200)`,
  err_list = gsub(
    "\\[|\\]", 
    "",
    `Xcontam ANGSD MOM 95% CI truncated at 0 (only if male and ≥200)`
    )
) %>%
  dplyr::filter(
    !is.na(xcon)
  ) %>%
  tidyr::separate(
    err_list, c("start", "stop"), sep = ","
  ) %>%
  dplyr::mutate(
    start = as.numeric(start),
    stop = as.numeric(stop)
  ) %>%
  tibble::as_tibble()

#### truncated normal theory ####

xcontam %>% dplyr::filter(
  xcon > 0, start > 0
) %>% dplyr::mutate(
  diff_mean_start = abs(xcon - start),
  diff_mean_stop = abs(xcon - stop)
)

```

```
# A tibble: 450 x 5
      xcon start  stop diff_mean_start diff_mean_stop
     <dbl> <dbl> <dbl>           <dbl>          <dbl>
 1 0.0110  0.003 0.019         0.00798        0.00802
 2 0.0333  0.007 0.059         0.0263         0.0257 
 3 0.0112  0.002 0.021         0.00924        0.00976
 4 0.0102  0.001 0.019         0.00923        0.00877
 5 0.00664 0.003 0.01          0.00364        0.00336
 6 0.00586 0.003 0.009         0.00286        0.00314
 7 0.00554 0.003 0.008         0.00254        0.00246
 8 0.00793 0.005 0.011         0.00293        0.00307
 9 0.00519 0.003 0.007         0.00219        0.00181
10 0.00733 0.005 0.01          0.00233        0.00267
# … with 440 more rows
```

**Comment by nevrome** [comment]
I think this issue is solved now: We basically decided to keep the value as we initially defined it:

> Xcontam_stderr: standard error of ANGSD X contamination estimate

And we also figured out how to get this value from the info in the anno file: https://github.com/poseidon-framework/poseidon2/blob/4d7f8c6ce54a42defe1371e7ca735e4be81d6f83/anno2janno/anno2janno.R#L181
